### ISSUE TITLE
请问这是研究生的学习资料吗

### ISSUE THREAD

**Issue by orion-orion** [dmclNewbee302/DMCL-2018#2]
我是一个双非学生，想报考电科，对你们实验室很有兴趣，请问这是研究生的学习资料吗

**Comment by ehds** [comment]
是的，研究生新生的学习资料。

**Comment by orion-orion** [comment]
谢谢，还有一个问题，就是你们平时做分布式系统项目用的什么语言呢，C++/Java/Go?

**Comment by ehds** [comment]
> 谢谢，还有一个问题，就是你们平时做分布式系统项目用的什么语言呢，C++/Java/Go?

C++和Go都有使用
